dataset:
  class_name: DataInitializer
  dataset_name: Planetoid
  name: CiteSeer
model:
  class_name: GraphConvolutionalNetwork
  in_channels: 3703
  num_layers: 2
  hidden_channels: 16
  out_channels: 6
parser:
  skip_parsing: True
task:
  class_name: GraphTask
  task_name: classification
  model: /model
  dataset: /dataset
losses:
  - class_name: CrossEntropyLoss
metrics:
  - class_name: Accuracy
training_loop:
  epoch: 800
optimizer:
  lr: 0.01
  weight_decay: 0.0005
