dataset:
  class_name: DataInitializer
  dataset_name: Planetoid
  name: CiteSeer
model:
  class_name: GraphAttentionNetwork
  in_channels: 3703
  out_channels: 6
  hidden_channels: 128
  num_layers: 2
  heads: 2
layer_wrapper:
  class_name: $GenericLayerQuantizerWrapper
  quantizer_function:
    class_name: LSQQuantizeFunction
  initializer:
    class_name: LsqInitializer
  range_observer:
    class_name: UniformRangeObserver
    bits: 8
activation_wrapper:
  class_name: $ActivationQuantizerWrapper
  quantizer_function:
    class_name: LSQQuantizeFunction
  initializer:
    class_name: LsqInitializer
  range_observer:
    class_name: UniformRangeObserver
    bits: 8
    is_positive: True
parser:
  class_name: TorchModelParser
  callable_object: /layer_wrapper
  callable_object_for_nonparametric: /activation_wrapper
task:
  class_name: GraphTask
  task_name: classification
  model: /model
  dataset: /dataset
losses:
  - class_name: CrossEntropyLoss
metrics:
  - class_name: Accuracy
optimizer:
  class_name: $Adam
  lr: 0.0001
scheduler:
  class_name: $OneCycleLR
  epochs: 120
  max_lr: 0.001
  steps_per_epoch: 100