dataset:
  class_name: DataInitializer
  dataset_name: Planetoid
  name: Cora
  transform:
    class_name: NormalizeFeatures
model:
  class_name: GraphAttentionNetwork
  num_layers: 2
  in_channels: 1433
  out_channels: 7
  hidden_channels: 64
  heads: 8
#  output_heads: 1
parser:
  skip_parsing: True
task:
  class_name: GraphTask
  task_name: classification
  model: /model
  dataset: /dataset
losses:
  - class_name: CrossEntropyLoss
metrics:
  - class_name: Accuracy
training_loop:
  epoch: 120
optimizer:
  lr: 0.005
  weight_decay: 0.0005