dataset:
  class_name: DataInitializer
  dataset_name: ImageNet
#  root: /data/samirm97cs/datasets/imagenet1000/
  root: /data/samirm97cs/datasets/imagenet/
  train_transform:
    class_name: Compose
    transforms:
    - class_name: RandomResizedCrop
      size: (224, 224)
    - class_name: RandomHorizontalFlip
    - class_name: ToTensor
    - class_name: Normalize
      mean: (0.485, 0.456, 0.406)
      std: (0.229, 0.224, 0.225)
  test_transform:
    class_name: Compose
    transforms:
    - class_name: Resize
      size: (256, 256)
    - class_name: CenterCrop
      size: (224, 224)
    - class_name: ToTensor
    - class_name: Normalize
      mean: (0.485, 0.456, 0.406)
      std: (0.229, 0.224, 0.225)
dataloader:
  batch_size: 256
  num_workers: 8
  pin_memory: True
model:
  class_name: ResNet18
  pretrained: True
layer_wrapper:
  class_name: $TransformationLayerQuantizerWrapper
  quantizer_function:
    class_name: LSQQuantizeFunction
  initializer:
    class_name: LsqInitializer
  range_observer:
    class_name: UniformRangeObserver
    bits: 8
activation_wrapper:
  class_name: $ActivationQuantizerWrapper
  quantizer_function:
    class_name: LSQQuantizeFunction
  initializer:
    class_name: LsqInitializer
  range_observer:
    class_name: UniformRangeObserver
    bits: 8
    is_positive: True
parser:
  class_name: TorchModelParser
  callable_object: /layer_wrapper
  callable_object_for_nonparametric: /activation_wrapper
  skip_layer_by_regex:
    - "^conv1$"
    - "^relu$"
    - "^fc$"
  skip_layer_by_type:
    - class_name: $AdaptiveAvgPool2d
    - class_name: $MaxPool2d
    - class_name: $BatchNorm2d
task:
  class_name: ImageTask
  task_name: classification
  model: /model
  dataset: /dataset
losses:
  - class_name: CrossEntropyLoss
metrics:
  - class_name: Accuracy
optimizer:
  class_name: $SGD
  lr: 0.01
  momentum: 0.9
  weight_decay: 4e-5
scheduler:
  class_name: $MultiStepLR
  milestones: (3, 30, 90)
  gamma: 0.1