dataset:
  class_name: DataInitializer
  dataset_name: Planetoid
  name: CiteSeer
model:
  class_name: SampleAndAggregateGraph
  in_channels: 3703
  out_channels: 6
  hidden_channels: 128
  num_layers: 2
  normalize: True
layer_wrapper:
  class_name: $CommunicationGraphQuantizerWrapper
  quantizer_function:
    class_name: STEOffsetQuantizeFunction
  initializer:
    class_name: MinMaxOffsetInitializer
  range_observer:
    class_name: MomentumMinMaxUniformRangeObserver
    bits: 8
    momentum: 0.01
    percentile: 0.001
  communication_quantizer_function:
    class_name: STEOffsetQuantizeFunction
  communication_initializer:
    class_name: MinMaxOffsetInitializer
  communication_range_observer:
    class_name: MomentumMinMaxUniformRangeObserver
    bits: 8
    momentum: 0.01
    percentile: 0.001
activation_wrapper:
  class_name: $ActivationQuantizerWrapper
  quantizer_function:
    class_name: STEOffsetQuantizeFunction
  initializer:
    class_name: MinMaxOffsetInitializer
  range_observer:
    class_name: MomentumMinMaxUniformRangeObserver
    bits: 8
    is_positive: True
    momentum: 0.01
    percentile: 0.001
parser:
  class_name: TorchModelParser
  callable_object: /layer_wrapper
  callable_object_for_nonparametric: /activation_wrapper
  skip_layer_by_type:
    - class_name: $MeanAggregation
task:
  class_name: GraphTask
  task_name: classification
  model: /model
  dataset: /dataset
losses:
  - class_name: CrossEntropyLoss
metrics:
  - class_name: Accuracy
training_loop:
  epoch: 150
optimizer:
  class_name: $Adam
  lr: 1e-3
scheduler:
  class_name: $MultiStepLR
  milestones: (40, )
  gamma: 0.1